on:
  push:
    branches:
      - master
  pull_request:
permissions:
  contents: read
  id-token: write
name: Build
jobs:
  build-amd64:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: "Read secrets"
      uses: rancher-eio/read-vault-secrets@main
      with:
        secrets: |
          secret/data/github/repo/${{ github.repository }}/github/release-app-credentials appId | APP_ID ;
          secret/data/github/repo/${{ github.repository }}/github/release-app-credentials privateKey | PRIVATE_KEY

    - name: Create App Token
      continue-on-error: true
      uses: actions/create-github-app-token@v1
      id: app-token
      with:
        repositories: release-flannel
        app-id: ${{ env.APP_ID }}
        private-key: ${{ env.PRIVATE_KEY }}

    - name: Set the TAG value
      id: get-TAG
      run: |
        echo "$(make -s log | grep TAG)" >> "$GITHUB_ENV"
    - name: Build container image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: false
        tags: rancher/hardened-flannel:${{ env.TAG }}-amd64
        file: Dockerfile
        build-args: |
          TAG=${{ env.TAG }}
          SRC=x-access-token:${{ steps.app-token.outputs.token }}@github.com/rancher/release-flannel

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@0.29.0
      with:
        image-ref: rancher/hardened-flannel:${{ env.TAG }}-amd64
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'

  build-arm64:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: "Read secrets"
      uses: rancher-eio/read-vault-secrets@main
      with:
        secrets: |
          secret/data/github/repo/${{ github.repository }}/github/release-app-credentials appId | APP_ID ;
          secret/data/github/repo/${{ github.repository }}/github/release-app-credentials privateKey | PRIVATE_KEY

    - name: Create App Token
      continue-on-error: true
      uses: actions/create-github-app-token@v1
      id: app-token
      with:
        repositories: release-flannel
        app-id: ${{ env.APP_ID }}
        private-key: ${{ env.PRIVATE_KEY }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set the TAG value
      id: get-TAG
      run: |
        echo "$(make -s log | grep TAG)" >> "$GITHUB_ENV"
    - name: Build container image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: false
        tags: rancher/hardened-flannel:${{ env.TAG }}-arm64
        file: Dockerfile
        outputs: type=docker
        platforms: linux/arm64
        build-args: |
          TAG=${{ env.TAG }}
          SRC=x-access-token:${{ steps.app-token.outputs.token }}@github.com/rancher/release-flannel

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@0.29.0
      with:
        image-ref: rancher/hardened-flannel:${{ env.TAG }}-arm64
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'